/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  编程语言: [
    'Home',
    {
      type: 'category',
      label: 'Java编程学习',
      link: {
        type: 'generated-index',
        //description: '',
        keywords: ['Java', '技术手册'],
      },
      items: [
        'Java概念'
      ]
    }
  ],

  reading: [
    {
      type: 'category',
      label: '读书笔记',
      link: {
        type: 'generated-index',
        // narbar的默认选择项
        slug: '/reading',
        //description: '',
        keywords: ['阅读', '笔记'],
      },
      items: [
        'reading/认知觉醒读书笔记'
      ]
    }
  ]
};

module.exports = sidebars;
